apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-cli-manager
  name: cli-manager 
  labels:
    app: cli-manager
  annotations:
    config.openshift.io/inject-proxy: operator
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cli-manager
  template:
    metadata:
      name: cli-manager
      labels:
        app: cli-manager
    spec:
      serviceAccountName: cli-manager
      containers:
      - name: test
        image: quay.io/sallyom/clustercli:latest
        imagePullPolicy: Always
        command: ["cli-manager"]
        args:
        - "cli-manager"
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
        - mountPath: /var/run/configmaps/trusted-ca-bundle
          name: trusted-ca-bundle
          readOnly: true
        - mountPath: /var/run/configmaps/service-ca-bundle
          name: service-ca-bundle
          readOnly: true
        env:
        - name: IMAGE
          value: quay.io/sallyom/clustercli:test
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
      - name: config
        configMap:
          defaultMode: 440
          name: cli-manager-config
      - name: trusted-ca-bundle
        configMap:
          name: trusted-ca-bundle
          optional: true
      - name: serving-cert
        secret:
          secretName: serving-cert
          optional: true
      - name: service-ca-bundle
        configMap:
          name: service-ca-bundle
          optional: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120 
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120 
