apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:clustercli
roleRef:
  kind: ClusterRole
  name: cluster-admin  # TODO fix
subjects:
- kind: ServiceAccount
  namespace: openshift-cli-manager
  name: cli-manager
